---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: honeycomb-api-key
  namespace: observability
spec:
  encryptedData:
    API_KEY: AgBGkFPjse3/oggUp9LNW5YlAPeqCBAPjHP0S0WX9ALE7pwxtBrB0UHGudtg5tb0DWkSY/A9CYWJA1sAvfwFFpDHloEWxRzacQJGIA/co8qDd2i6Crv5jvSxSgbMiQtl5ly2HwjATpfR2ZM+VzB8n6R2LiURyPVOVEPOd91FIwGAjDRna5DmqyAgoc/z8KQJZuBAowzcatUw/4w/0Dna6nuuLatUKdAQGtaq0IylvViwFYj0puTGN675vJN5mDZYgkmF5jZ3fRS9vR1HVm+/nksrgHd1iYL2N8G0v2ax+GSKG6nJ2PUprlLLd8sLYtefmoZGype8XozMQpnI7DJRsXyQngSsEu4vLMqHnTBF2K8EckESBukg2A4eXYhJV729KtXOCz99zPXKkTwfTi/Rd3wpPl1bwV9RARWRFmF2E2smjpFc/rVlODXim+5I01WWqRWkhLQCpfQsz3x/viorsxqx4mq2zULPfDn6oQ/u0PMAEr2xxjR/CJCDDyqsJqK0ScA0Ve9QYHw/GlTpML2bETO58FBjH9quAYvsRC+Y/SLe7hArmilWVg65KpUe5fANWMGPv7cuedccT/e8CkQCerWcPVySzyjblytXZd5loQajPS1SpwRbzPTPbTx1UFjBXqBq/WtJgh7qPbMIiTALDCXr6Cn4JTqwHX+Hcr9LQpnogNOkTC557OWOY//kTILBJpmxIJSYliuSs3Vn31JgatBJbCpzdNVr
  template:
    metadata:
      creationTimestamp: null
      name: honeycomb-api-key
      namespace: observability
