---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: splunk-api-key
  namespace: observability
spec:
  encryptedData:
    API_KEY: AgBrkKQAQBdAfsNCQA+TgS1fB1A2a5vn0xrqrEW+AoM5aJm5MCfbJ1nWfgGECjtktLV8yW+Im26/SgZD7XcGnE7gfQ+y0ffvnmXLKGPcUGMlIwZA1LLbMrR6xlprcAJQz6Il7GhEIIdLb9rSAJdsDsmKEHgoNzCz/7hdeC8wd3IbwJSZt0hjPqDAeNDKz9i4JinbbjEXQd1HPvRKZa4GtiSqNYuCRBYzMHm3CEW/CxJNJn8CSGjdKfxVTs0OULnwBkmfRf6zVZpE5wb30DD18DjwBPlUS8NHWQnBvEZG/ifAgUr3gpOgeClDVfGeSMT1ArcW0PAFaYmCub80pXdMdzYP+j5s+2hSy3vZ/wCMGSIXYE6Ml2HftjRpFQ4JxMpM976QWant7eMd1sZPCaKMVLyFlQ7eSlDDV6REPgR5Mjw6EgblJK+cqw/kM0EzusVkqG/lfAMOWuP2yrbBGaPs69ynsKVDQmBX1trHQm5l41QQKsTsMxW6QZ7kPubdfpvqW5nFC8kVuDRzd+pNf3KjHNkHsIrsdFTuL64Ru8MlOJEbAMMpGFYvqQ3uLPuNIoXMGNja3dm4FFsPcSrNgRwSQ8EYz1Qpe3aXzGUkiOoYJulKJWHWS/Eb8j5G4h2sycAVOxuzWRk5xVqlAAJSwOXG3S6mbNGLPNiNA3glRto/gGmsdY2NMkNCFHZ23FLp2D6eM22h4/4EGDfQFbfIpemo1tWRLNxmoIDm
  template:
    metadata:
      creationTimestamp: null
      name: splunk-api-key
      namespace: observability
