---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authsecret
  namespace: observability
spec:
  encryptedData:
    users: AgALv93621pszVI6siEsRDTW9hsxEfzQAZwWsIsKbqSeyUXxCBBzNS+dHY7zLsnjDK2ulC5/p7ijHOz941ksyO6+c+GpPQ8qhfQB/NVEeufGcxhikKJJaWBRprKlmg0WUrnOCehzhjnw5LlvOYrz0BjoFHRepTJcmZd7oQNI4klpwkblFdHS4iNp+txZecmCvQUkvT838CyoK7YziW5BreIaondJKrOMSMHbueoiasfqfYxFU8YVAfSwmFNHNQzvkpb/6USZK2e4XmLpEMaBFj84ysDmk0opDWiFRL/7IWWhautQ8KNvG8id0bo6SASa4GG6uaIWIPfh6w4oQERZ2ypkiOgya2tE3y3WyVzU1qGlXYKLlob/pqaqcl/MiZ6paJtXVcN75q1kK8QZclJwhd+edeaXok88x4yMsvKM/2ZZp/zf+4HzpDMl3HSfyl/qIsWEiDV8g6L4u+SJMjYW610gYN3llIR8k1wIf5toJyCc1QYqAEYL5OcneR1jE+NCHYYJw/i/FWpfELCsXwAMX0ijcNiEhuGBdFgHQj2yy2yTYbvFJkDfcwsQd6QJ08TPtf8hXLNwssN3GTSzosK2AVeUQg8PUdG+MO+OyXOWSh9DesoY0tkL+J3qyhNQJe3jYTDdMepbVZnVSnO/kwOUp49fk02x5A7VA6RV+tyiZWf0yIHTa0L0yXE4lb2gfYH2qn35warPT3fWG5ytaB8Mw3kZiXfax36dSh/xbcdS/QIJQModLz3YHRQDO8m/5w==
  template:
    metadata:
      creationTimestamp: null
      name: authsecret
      namespace: observability
