apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://fluent.github.io/helm-charts" # public repo
      chart: fluent-bit
      targetRevision: "0.48.10"
      helm:
        valueFiles:
          - $values/apps/fluentbit/values.yaml
    - repoURL: "https://github.com/jjgrinwis/observability-stack" # repo with our ingress route
      ref: values
      targetRevision: HEAD
    - repoURL: "https://github.com/jjgrinwis/observability-stack" # repo with our ingress route
      path: apps/fluentbit/ingress
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: observability # Namespace where Fluent Bit will be deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
